// Generated by CoffeeScript 1.4.0
(function() {
  var Address, address1, address2, address3, address4, address5, address6, validateAddress, validator, _;

  validator = require('./index');

  Address = validator.Address;

  _ = require('underscore');

  address1 = {
    street: '100 North Washington St',
    city: 'Boston',
    state: 'MA',
    country: 'US'
  };

  address2 = {
    street: '100 North Washington St',
    city: 'Poop',
    state: 'MA',
    country: 'US'
  };

  address3 = {
    street: '1 Shitstorm St',
    city: 'Boston',
    state: 'MA',
    country: 'US'
  };

  address4 = {
    street: '1 Main St',
    city: 'San Diego',
    state: 'CA',
    country: 'US'
  };

  address5 = {
    street: '12 proctor rd',
    state: 'Massachussetts',
    country: 'US'
  };

  address6 = {
    street: '1 Main St',
    city: 'San Diego',
    country: 'US'
  };

  validateAddress = function(input) {
    var inputAddress;
    inputAddress = new Address(input);
    return validator.validate(inputAddress, function(err, validAddresses, inexactMatches) {
      console.log('input: ', inputAddress.toString());
      if (err) {
        console.log(err);
      } else {
        console.log('address: ', _.map(validAddresses, function(a) {
          return a.toString();
        }));
        console.log('did you mean: ', _.map(inexactMatches, function(a) {
          return a.toString();
        }));
      }
      return console.log('\n');
    });
  };

  validateAddress(address1);

  validateAddress(address2);

  validateAddress(address3);

  validateAddress(address4);

  validateAddress(address5);

  validateAddress(address6);

  validateAddress('12 proctor rd townsend, Mass');

  validateAddress('100 north washington st, bostont');

  validateAddress('Boston, MA');

  validateAddress('Boston, MA, USA');

  validateAddress('MA');

  validateAddress('Sibirskaya 22, Novosibirks, Russia');

}).call(this);
