// Generated by CoffeeScript 1.9.3
(function() {
  var Address, _, addressMatch, defaultMatchType, matchType, matchUnknownType, options, request;

  _ = require('underscore');

  request = require('request');

  options = {
    countryBias: "us",
    countryMatch: null,
    key: null
  };

  exports.setOptions = function(opts) {
    return _.extend(options, opts);
  };

  matchUnknownType = function(known, unknown) {
    var compare, find, found, foundProps, haveProps, i, len, otherAddress, prop, props, value;
    compare = (function(_this) {
      return function(prop) {
        if (known[prop] && unknown[prop]) {
          if (known[prop].toLowerCase() === unknown[prop].toLowerCase()) {
            return true;
          }
          if (unknown.generated && unknown[prop + 'Abbr']) {
            return known[prop].toLowerCase() === unknown[prop + 'Abbr'].toLowerCase();
          } else if (known.generated && known[prop + 'Abbr']) {
            return known[prop + 'Abbr'].toLowerCase() === unknown[prop].toLowerCase();
          } else {
            return false;
          }
        }
        return !known[prop] && !unknown[prop];
      };
    })(this);
    if (known.isObject && unknown.isObject) {
      return compare('city') && compare('state') && compare('country');
    } else if (known.isObject && !unknown.isObject) {
      props = ['streetNumber', 'street', 'city', 'state', 'country', 'postalCode'];
      otherAddress = unknown.toString().toLowerCase();
      if (known.toString() === otherAddress) {
        return true;
      }
      foundProps = 0;
      haveProps = 0;
      find = function(val) {
        var oldlen;
        val = val.toLowerCase();
        oldlen = otherAddress.length;
        otherAddress = otherAddress.replace(new RegExp("\\b" + val + "\\b", "i"), "");
        if (oldlen !== otherAddress.length) {
          foundProps++;
          return true;
        }
        return false;
      };
      for (i = 0, len = props.length; i < len; i++) {
        prop = props[i];
        value = known[prop];
        if (value !== void 0) {
          found = find(value);
          if (!found && (prop === "state" || prop === "country" || prop === "street") && known[prop + "Abbr"] !== void 0) {
            found = find(known[prop + "Abbr"]);
          }
          if (!found && prop === "country" && value.toLowerCase() === "united states") {
            found = find("usa");
          }
          if (!found && prop === "street") {
            value = value.replace(/( street)/i, ' st');
            found = find(value);
            if (!found) {
              value = value.replace(/( road)/i, ' rd');
              find(value);
            }
          }
          if (!found && prop === "postalCode") {
            haveProps--;
          }
          haveProps++;
        }
      }
      otherAddress = otherAddress.replace(/[ ,]/g, '');
      return foundProps === haveProps && otherAddress.length === 0;
    } else {
      return known.toString().toLowerCase() === unknown.toString().toLowerCase();
    }
  };

  addressMatch = {
    streetAddress: [
      {
        location_type: "ROOFTOP",
        types: ["street_address"],
        exact: true
      }, {
        location_type: "RANGE_INTERPOLATED",
        types: ["street_address"],
        exact: false
      }
    ],
    route: [
      {
        location_type: "GEOMETRIC_CENTER",
        types: ["route"],
        exact: true
      }
    ],
    city: [
      {
        location_type: "APPROXIMATE",
        types: ["locality", "political"],
        exact: true
      }
    ],
    state: [
      {
        location_type: "APPROXIMATE",
        types: ["administrative_area_level_1", "political"],
        exact: true
      }
    ],
    country: [
      {
        location_type: "APPROXIMATE",
        types: ["country", "political"],
        exact: true
      }
    ],
    unknown: [
      {
        location_type: "unknown",
        types: ["unknown"],
        exact: true
      }
    ]
  };

  exports.match = matchType = {};

  _.each(addressMatch, function(list, name) {
    return matchType[name] = name;
  });


  /*
      Address object that provides useful methods. Create a new one by
        1. passing a map with these props: {street:'123 main st', city: 'boston', state: 'MA'|'massachussetts', country: 'US'|'United States'}
          None of the props are required, but chances are you wont have a valid address if you omit any of them (except for state)
        2. passing a string containing an address (the address class does not parse the string into parts)
        3. passing a result object from a google geocoding response. ie: geoResponse.results[0]
  
  
      The validator.validate callback will return to you these objects, except they will have all or some of the following properties:
          streetNumber: '100'
          street: 'North Main St'
          streetAbbr: 'N Main St'
          city: 'Boston'
          state: 'Massachussetts'
          stateAbbr: 'MA'
          country: 'United States'
          countryAbbr: 'US'
          postalCode: 02114
          location: {lat: 43.233332, lon: 23.2222243}
  
      Methods:
          toString(useCountryAbbr, useStateAbbr, useStreetAbbr) - returns a string representing the address. currently geared towards North American addresses
              useCountryAbbr = [optional] default: true - the resulting address string should use country abbr, not the full country name
              useStateAbbr   = [optional] default: true - the resulting address string should use state abbr, not the full state name
              useStreetAbbr  = [optional] default: false - the resulting address string should use street name abbr, not the full street name
              Note: the abbriviated values will only be used if they are available. The Address objects returned to you from the validate callback may have these available.
          equals(anotherAddress) - check if 2 addresses are probably* the same. IT DOES NOT CHECK STREET NAME/NUMBER
   */

  exports.Address = Address = (function() {
    Address.prototype.matchType = matchType.unknown;

    Address.prototype.exactMatch = null;

    function Address(address, isObject, generated) {
      var city, country, countryAbbr, getComponent, location, postalCode, postalCodePrefix, ref, ref1, ref10, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, state, stateAbbr, street, streetAbbr, streetNum, x;
      this.isObject = isObject != null ? isObject : false;
      this.generated = generated != null ? generated : false;
      if (_.isObject(address)) {
        this.isObject = true;
        if (address.address_components) {
          this.generated = true;
          location = {
            lat: (ref = address.geometry) != null ? (ref1 = ref.location) != null ? ref1.lat : void 0 : void 0,
            lon: (ref2 = address.geometry) != null ? (ref3 = ref2.location) != null ? ref3.lng : void 0 : void 0
          };
          this.exactMatch = !address.partial_match;
          _.each(addressMatch, (function(_this) {
            return function(list, name) {
              return _.each(list, function(obj) {
                if (obj.location_type === address.geometry.location_type && _.difference(obj.types, address.types).length === 0) {
                  _this.matchType = name;
                  if (!obj.exact) {
                    return _this.exactMatch = false;
                  }
                }
              });
            };
          })(this));
          getComponent = this.componentFinder(address.address_components);
          ref4 = getComponent('street_number', false), x = ref4[0], streetNum = ref4[1];
          ref5 = getComponent('route', false), streetAbbr = ref5[0], street = ref5[1];
          ref6 = getComponent('locality'), x = ref6[0], city = ref6[1];
          ref7 = getComponent('administrative_area_level_1'), stateAbbr = ref7[0], state = ref7[1];
          ref8 = getComponent('country'), countryAbbr = ref8[0], country = ref8[1];
          ref9 = getComponent('postal_code', false), postalCode = ref9[0], x = ref9[1];
          ref10 = getComponent('postal_code_prefix', false), postalCodePrefix = ref10[0], x = ref10[1];
          address = {
            streetNumber: streetNum,
            street: street,
            streetAbbr: streetAbbr,
            city: city,
            state: state,
            stateAbbr: stateAbbr,
            country: country,
            countryAbbr: countryAbbr,
            postalCode: postalCode,
            postalCodePrefix: postalCodePrefix,
            location: location
          };
        }
        _.each(address, (function(_this) {
          return function(val, key) {
            return _this[key] = val;
          };
        })(this));
      } else {
        this.addressStr = address;
      }
    }

    Address.prototype.componentFinder = function(components) {
      return function(type, type2) {
        var it;
        if (type2 == null) {
          type2 = "political";
        }
        it = _.find(components, function(c) {
          return c.types[0] === type && (!type2 || c.types[1] === type2);
        });
        return [it != null ? it.short_name : void 0, it != null ? it.long_name : void 0];
      };
    };

    Address.prototype.toString = function(useCountryAbbr, useStateAbbr, useStreetAbbr) {
      var arr, countryVal, i, len, prop, ref, stateVal, str, streetVal;
      if (useCountryAbbr == null) {
        useCountryAbbr = true;
      }
      if (useStateAbbr == null) {
        useStateAbbr = true;
      }
      if (useStreetAbbr == null) {
        useStreetAbbr = false;
      }
      if (!this.isObject) {
        return this.addressStr;
      }
      arr = [];
      stateVal = useStateAbbr && this.generated ? 'stateAbbr' : 'state';
      countryVal = useCountryAbbr && this.generated ? 'countryAbbr' : 'country';
      streetVal = useStreetAbbr && this.generated ? 'streetAbbr' : 'street';
      ref = [streetVal, 'city', stateVal, countryVal];
      for (i = 0, len = ref.length; i < len; i++) {
        prop = ref[i];
        if (this[prop]) {
          arr.push(this[prop]);
        }
      }
      str = arr.join(', ');
      if (this.streetNumber) {
        str = this.streetNumber + " " + str;
      }
      return str;
    };

    return Address;

  })();


  /*
      validate an input address.
  
      inputAddr: validator.Address object or map with 'street', 'city', 'state', 'country' keys, or string address
      cb: function(err, validAddresses, inexactMatches, geocodingResponse)
          err - something went wrong calling the google api
          validAddresses - list of Address objects. These are exact matches to your input, and will have proper spelling, caps etc. Its best that you use this instead of what you had
          inexactMatches - list of Address objects. Incomplete addresses or addresses that do not match your input address. useful for 'did you mean?' type UIs
          geocodingResponse - the json object that i got from google API
   */

  defaultMatchType = matchType.streetAddress;

  exports.validate = function(inputAddr, addressType, cb) {
    var inputAddress, opts, protocol, qs;
    if (addressType == null) {
      addressType = defaultMatchType;
    }
    if (arguments.length === 2) {
      cb = addressType;
      addressType = defaultMatchType;
    }
    inputAddress = inputAddr instanceof Address ? inputAddr : new Address(inputAddr);
    qs = {
      'sensor': false,
      'address': inputAddress.toString(),
      region: options.countryBias,
      language: options.language
    };
    if (options.countryMatch) {
      qs.components = "country:" + options.countryMatch;
    }
    protocol = 'http';
    if (options.key) {
      qs.key = options.key;
      protocol = 'https';
    }
    opts = {
      json: true,
      url: protocol + "://maps.googleapis.com/maps/api/geocode/json",
      method: 'GET',
      qs: qs
    };
    return request(opts, function(err, response, body) {
      var inexactMatches, validAddresses;
      if (err) {
        return cb(err, null, null, body);
      }
      if (response.statusCode !== 200) {
        return cb(new Error("Google geocode API returned status code of " + response.statusCode), [], [], body);
      }
      if (body.status.toLowerCase() !== "ok") {
        return cb(new Error("Google returned error: " + body.status + " - " + body.error_message), [], [], body);
      }
      if (body.results.length === 0) {
        return cb(null, [], [], body);
      }
      validAddresses = [];
      inexactMatches = [];
      _.each(body.results, function(result) {
        var address;
        address = new Address(result);
        if (addressType === matchType.unknown) {
          if (matchUnknownType(address, inputAddress)) {
            return validAddresses.push(address);
          } else {
            return inexactMatches.push(address);
          }
        } else if (addressType === address.matchType) {
          if (address.exactMatch) {
            return validAddresses.push(address);
          } else {
            return inexactMatches.push(address);
          }
        }
      });
      return cb(null, validAddresses, inexactMatches, body);
    });
  };

}).call(this);
